:PROPERTIES:
:ID:       d0072402-2a3e-4f4c-b56e-a8d56fd53a77
:END:
#+title: trst
#+filetags: :poem:greek:

* trst
Thirsty
you let me have just a sip, from your glass of water.
quenching my thirst, yet I yearn for more.
you look down into the glass, and see that it’s empty.
so you hide it from me, and try to distract me.
but I’m only human, and I need to drink.

you don’t say anything, you hand me a glass.
and show me the door, meadows and land.
so I go searching, for a pond or lake.
and promise that someday, I’ll come back with a cake.

your illusions of gardens, crumble to sand.
through the endless wasteland, I crawl on my hands.
i keep on going, through the plights and through the plunders.
but i wont ever reach the fata morganas, what seems like days start blending into months

within 27 days, I reach your shack again.
the hard cherry wood, soft my blood red eyes.
but before i can even reach the door,
i fall into a slumber right at your porch.

I dream of oceans, swimming pools galore.
an infinite dream, an everlasting dream.
you stare at the skull, at the foot of your door.
you sigh and stare, whispering a prayer.
you pick up the head, carry it into the house.
you take a large knife, cut straight into the bone.
you drip the fresh water, into glass for the next, who knocks on your door.

still i’m sorry, my dear Calypso.
for even in my slumber, i miss your short raven hair.
your soft cold touch, your imperfect laugh.
your warm loving gaze, your fragant scent in the wind.
<2023-06-26 Mon>
