:PROPERTIES:
:ID:       e1b86d14-0e7e-4a1c-9fe4-da98ec7e26a3
:END:
#+title: dnbk
#+filetags: :story:

* dnbk
For not even having a library card yet, Lyla didn’t anticipate taking a book home from the library today.

The soft pale mauve cover book stood out from the orderly rows of thicker black reference books, pulling at her attention. Reluctantly, she pulled the book down from the shelf and flipped it open to the first page. The inside of the inside had been intricately decorated with a thin black marker. The bottom of the purple page was filled with mushrooms of various shapes and sizes as well as grass and small flowers. Above that lay a with a drawing of a small house with a garden. The house was drawn with each brick in mind, the cracks and variation in patterns had been drawn with intent and purpose.The garden was too labeled with the names of the plants and their scientific names. The page was filled with a variety of other drawings and labels, all in the same impossibly thin black ink.

<2023-06-25 Sun>
