:PROPERTIES:
:ID:       722ef026-d9f8-4812-ad06-79d297151283
:END:
#+title: The crisis of staple foods
#+filetags: :essay:economics:food:

*  The crisis of staple foods
Staple foods, ailemnts de base, are key foods that are prevalaent in certain lesser-developed societies. This is due to their firm positioning in the ecological system. Agricultural societies of the past took these staple foods like rice, potato, wheat and millet in order to sustain their diet. This choice was made, as the name would suggest, is because these foods could resist ecological or environmental fluctuations, and thus was an stable investment for humans to make. As a result the diets of whole communities, especially in poorer regions, because dependent on the harvest of a single plant. An example of this how Nepali communities are so dependent on millet to the point where there local government tends to subsidize it and Old Irish Villages dependency on potatos.

As you may figure, a completely reliance on a singular crop carries terrible risks to individuals and societies. At a large scale, a whole vilalge is easily vulnerable to a unforseen shift in weather or incursion of a natural disater. A singular drought or famine for a certain crop could wipe out a majority of the population in one fell swoop.

Furthermore, the effects of relying on a staple crop for all meals is terrible for human diet. A human diet needs to be varied in order to supply our body with all the macro and micro nutrients it needs to function. Unfortunately no singular crop is a "super food" and is unable to provide us with all of the nutrients we require. This further mentally and physically cripples those in the communities, forcing them to remain stuck in a undeveloped and often impovershed status.

In conclusion, this is why its extremely important for us to have a balanced of a diet as possible. We should all take a note out of our ancestors who were foragers and gatherers. They constantly were moving around, eating different types of food whatever they could find and not forcing an inherently flawed crop to be over cultivated. This key focus on our diet and what we eat will allow ourselves to maximise our lives potential.
<2024-10-08 Tue>
