:PROPERTIES:
:ID:       defamation
:END:
#+title: Why defamation of lazy people creates a hardworking population
#+filetags: :essay:economics:psychology:

* Why defamation and public humiliation of laziness create a hardworking population

In India, it's comon to see impovershied beggars and low wage workers constantly slacking and sleeping. I mean to take no offense to them personally, but their public exhibition of laziness creates a mental link in the observers relating those who are lazy or sleeping all the time and being in the lowest class of human beings.

The effect is exemplified through the contrast between me and my father at home. my father, who grew up in india  and was exposed to the lower cases, developed a natural inhibition towards laziness most commonly portrayed through sleeping during the day or slacking off. On the other hand, since I was raised in a developed country, I did not witness such behaviour and form those links.

This lead to several arguments, where I am convinced that me napping during the day is just to recuperate physical and mental strength, while my dad believes that I have become lazy and complacent.

Although this is not a bad mentality for societ to adopt, it presents how easily prejudcies can be formed in our soicety through our constant judgement. It also showcases a form of neurological evolution as a result of social interactions. People observee that being lazy is frowned upon, and thus strive to be productive to the economy in order to achieve most peoples common goal of societal acceptance.
<2024-10-21 Mon>
