:PROPERTIES:
:ID:       e230f7e4-1a02-4262-920b-c43a020495a8
:END:
#+title: Paper 1 broad skills
#+filetags: :essay:english:guide:

* Paper 1 broad skills
** The Guiding Questions and Theses
It's probably impossible to emphasize just how much this matters. If you do not center your analysis around the guiding question, you will *not* get high marks. Simple as that.
Let's look at a range of guiding questions:


How is the significance of the death of Mr. Mallard established and developed in this passage?
In what ways does the use of imagery help to create atmosphere in the poem?
What tensions are created in the descriptions in these paragraphs
How are the relationships between the characters presented in this extract?
How does the poem’s form contribute to its mood and the development of ideas?
How personification/metaphor/simile used in this poem to portray the night?
How does the poem use compressed/concentrated language to express complex ideas and/or feelings?

Although not always the case, we can notice that most guiding questions outline a technique and sometimes its effect.
Why is this important? Because it will serve as a foundation for our *thesis statement*.
First, let's talk about our *thesis statement*, an effective thesis will plan an argument for us. This is because an argument tends to lend to a predetermined essay structure.
How do we create this argument? Well, once you read the text, there is almost always an interplay/dichotomy/tension between two key concepts creating the effect. Nine out of ten times, it's Nature vs. Artificial. Nature vs. Artificial is always a good argument to make, and it's so prevalent everywhere.
So how does the technique play into making the argument? We can split our general technique into the two key concepts again. This is better shown with an example.
Say our technique provided is Imagery. Taking Nature vs. Artificial, the beginning of our *thesis statement* can take the form of
The author presents a dichotomy/tension between natural imagery and artificial imagery in order to create effect.
Now, you need to also be careful when implementing the effect. You absolutely need to discuss a specific effect. What do I mean by that?
Say, for example, our effect is Atmosphere. We cannot just say in order to create atmosphere, but what type of atmosphere? This could be melancholic or eulogical, maybe foreshadowing, cacolgic, nostalgic, hopeful or reminiscent. You get my point, try to be specific and correct to the text about the type of effect created.
And finally, possibly most importantly, we have the part that the question will not ask. Why?. In your essay, you must answer why the effect is being created through the technique. Here, we need to consider the authorial intent or edifying message.
This will help us finalize our *thesis statement*.
The author presents a dichotomy/tension between natural imagery and artificial imagery to create an effect  in order to convey an idea …
However, our why will go further than just the introduction's *thesis statement*, in our conclusion, we must also consider the global and wider perspective of the reader in relation to the edifying message. You want to say something insightful and nuanced about the text and how it relates to literature as a whole.
So to recap, our *thesis statement* presents a dichotomy or tension between two sides of a technique, to create a specific effect in order to convey an idea. And our conclusion focuses on the wider implications of this idea the author raises.

** The Structure
You have a few options for structuring your essay. Assuming that we are aiming for an introduction, 3 body paragraphs and a conclusion, you can either structure it thematically, chronologically or technically.
A technical structure would lend the topic sentence of each body paragraph to a certain technique, and the effect is created.
A chronological structure will analyze the text in the same order that the text would be read.
A thematic structure will focus each body paragraph on a specific theme, in relation to the question.
All of these structures have their pros and cons, and I won't be the one to tell you which one to use, as it depends on your style.
However, what I will suggest using is a mixed structure that develops off of your thesis. What do I mean? If you followed the same way to create a thesis as outlined above, you can structure your body paragraphs based off of your argument.
The first thematic technique, perhaps Natural Imagery and the effect it builds
The second thematic technique, Artificial imagery and the effect it builds.
The interplay/tension between the two techniques and the effect it builds.
This lends very well while planning, as you don't actually need to plan your structure beyond the thesis!
<2024-10-09 Wed>
