:PROPERTIES:
:ID:       artist-standpoint
:END:
#+title: An artists tendency to have strong standpoints
#+filetags: :essay:art:protests:crucible:communism:misogyny:american:plays:

Many artists are known to be highly controversial. They typically constantly defy societal expectations, are a higher class than most people and yet are adored by the masses. Why is this?

Recently we studied about Arthur Miller, a strong criticst of the American Dream. He was often unfairly accused of being a communist due to his connections and associations. We will use him as an analysis point for this claim.

Lets first begin with why he was a strong crictist. Arthur Miller was born in Harlem, New York City with two successful middle class workers for his parents. Following the Wall Street crash of 1929, the Miller family fell into a crisis. Suddenly, their house in Harlem and their summer house were sold for a chummy place in Brooklyn. Throughout his childhood, Arthur Miller experienced both the highs and lows of the American Dream. He learned from an early to be a rationalist criticist.

Once Arthur Miller started his career. His plays tended to criticized the American Dream, such as the play, "Death of a Salesman", where Miller grapples with the loss of identity and a mans fall following an ability to accept change within himself and society. This play was heavily criticized and boycotted by the American Legion due to the themes that were critical of the American Dream and capitalism. Through the "Death of a Salesman" Arthur Miller presented a strong criticism against the lusted-over American Dream.

Likewise, the play "The Crucible" was a commentary of the Red Scare and McArthyism induced fear and anxiety in the American society as well as the atmost unfair treatment. "The Crucible" achieved this by reflecting the contemporary issue with the Salem Witch trials of the late 1700's. The Crucible was so popular and sucessful, that it single handed made the Salem Witch Trials famous. On an even deeper level, Arthur Miller himself was persecuted with the same accusatory trials that the Salem Witch Trials showcases as injust and unfair. What likely influenced Miller to write this play was his connections to the League of American Writers, comprised mostly of communists, as well as the Federal Theatre Project, which got closed in 1939 due to Congress worries over Communist infiltration.

Arthur Miller was also born Jewish-Polish, although he was never overly religious, he often spoke out against anti-semistic behaviour and attempted to get many plays showcased about anti-semistism. However, these plays were never shown to an audience due to the American Theatre refusing to deal with controversial topics. In frustration that his plays were constantly being denied, Arthur Miller decided to write a speech titled "Concerning the Jews who Write" and later his first novel "Focus", a titular reference to jewish concentration camps, discusses discrimination in post World War 2 America and the issue of scapegoating.

< I could another reference to how Arthur Miller was against Misogyny and refused to sexually exploit Marilyn Monroe, but thats not a good point >

So we can see how several societal aspects can influence an artists life and cause them to stand out and voice their opinions. This key trait they have makes them unique and sought-after, raising them to fame and popularity. We can observe the raw desire for controversy and change humans encompass and the extent to which they idolize but also criticize those who embody it.

<2024-10-18 Fri>
