:PROPERTIES:
:ID:       reso
:END:
#+title: reso
#+filetags: :resolutions:change:

reso -> Resolutions

or maybe new years resolutions.

So, I did write resolutions last year, I can read it write now.

its really not that accurate though. I did manage to do some of the stuff, but I think the real issue was in the resolutions.

Now that I think back over them, they were alot of things that I wanted to achieve in the moment.

It really wasn't something that I thought over a long period of time, I really didn't understand the concept of a year even that well.

Now thats not to say I haven't accomplished anything this year, I am really proud on what I've managed to complete.

I'm just a bit scared that I won't become to attached to the winning or the goal side of things.

Enjoying the journey is really fun and managing to keep the motivation for it is the hardest part.

It's even more interesting to how I believe I could have done alot more this year.

But I think that just implies of how much more I can accomplish in the following years.

I wonder if I will write new years resolutions this year, however, I think if you want to get things done, don't wait for the new years to start? you know. (check out ruff's youtube videos if you have the time, he deserves the praise and is really good).

Just do it now. The haters don't know us.

only the real mf's read this blog.

peace out, love you.
