:PROPERTIES:
:ID:       sts
:END:
#+title: sts
#+filetags: :ramblings:stats:

sts -> stats

I like to think that I am a data-driven person. I feed information into my brain and it pumps out models, probabilities, choices and paths for me. But the algorithms that my brain probably uses are far to complex for me to gauge or even understand from a higher level perspective

I've never felt terribly wrong by my predictions. Every once in a while a small prediction is not true, especially when its far fetched. But the negative feedback also helps me adjust and fine tune my gut instinct.

The major problem is that the functions take in alot of data. They act a bit like chaotic functions. A small change in the input data can make me determine a completely new outcome.

To be honest it would be unfair for me to "claim" that these are functions. Functions typically map several points to one or one point to one. Several points to several points is not a function.

So whenever I garner new information, the outcomes update. The side effect is that this takes time to process in my head. Meaning I need to set aside time for to think about it. Usually I can do it in the background, when I'm walking, commuting or just doing simple work.

The times when I feel like data affecting my entire life has changed, I usually daydream for a couple of hours, staring at my ceiling on my bed or just light sleeping trying to process and see the new patterns and outcomes that have changed greatly.

It feels like when a whole scientific community does a paradigm shift and every theorem and model needs to update, except on a much smaller scale and with the only worker being my brain.
