:PROPERTIES:
:ID:       szns
:END:
#+title: szns
#+filetags: :poem:seasons:

szns -> seasons

- When seasons change, I feel dead \\

I think I may \\
fall in love in October \\
but as halloween comes around \\
I'm too spooked \\
to walk down these roads \\

So I decide to run. \\
run hard, run fast, run long \\
run till the thoughts in my head \\
freeze just like the weather. \\

Another month goes by, \\
and your merino red sweater \\
is pulled over my bear chest \\
I mark the 3rd \\
on the calendar \\
a sweet reminder \\

you and me are like glue \\
radiating our way through the bitter cold \\
leaving behind a sweeter road. \\
you tell me of your past \\
I made you my present \\
we dream of a future together. \\

3 months pass by \\
the flowers we planted in full bloom \\
the colors rich, and the petals a plenty \\
we dance around \\
our home \\
rhythmic clicks, linoleum tiles \\

but I guess, \\
4 is unlucky, the Chinese warn \\
you leave a ghost, \\
and I lose, my you. \\

The flowers we planted, \\
Have no fruits to bear \\
Nevertheless I grasp on \\
to the stems of the roses; \\
blood thorns embed my hands.
The long heat comes \\
with that the drying of leaves too \\
I remain confined in my room \\
in a coma, on my desk \\
studying reading writing \\
distracting myself \\
from everything about you. \\

As the fall rolls around \\
and the heat waves end. \\
I become love sick with you \\
once again. \\
I dance alone in the kitchen \\
wishing my feet would dance \\
like they did with you. \\
I would have died for you, \\
but you already did for me \\

/fn:/
- inspired by like 8 different songs
